### ISSUE TITLE
implement tidyverse coding convention

### ISSUE THREAD

**Issue by hannesdatta** [hannesdatta/marketingtools#1]

**Comment by hannesdatta** [comment]
`reshape2` has been deprecated. change code so reshape is called from `tidyverse`

**Comment by hannesdatta** [comment]
@JoepvanderPlas, can you handle this, please?

**Comment by JoepvanderPlas** [comment]
I changed the dcast function to the pivot_wider function (from the tidyverse package)

**Comment by JoepvanderPlas** [comment]
@hannesdatta after accepting the pull request, you can close this issue.

**Comment by hannesdatta** [comment]
thanks a bunch!
