### ISSUE TITLE
re-structure entire package according to devtools

### ISSUE THREAD

**Issue by hannesdatta** [hannesdatta/marketingtools#6]
The package loading now doesn't properly work. It's important to port the entire infrastructure to the way I set up github.com/hannesdatta/musicMetadata (i.e., with documentation inside the R functions), etc. Maybe also start "clean" (new branch) and then integrate new functionality one by one.

**Comment by hannesdatta** [comment]
@JoepvanderPlas, this will take a day or two for me to get done. fine?

**Comment by JoepvanderPlas** [comment]
Thats fine!

**Comment by hannesdatta** [comment]
follow-up issues to create when I'm done

- document data

<img width="572" alt="image" src="https://user-images.githubusercontent.com/16557730/133421966-d46fc56d-8b19-4656-bc8e-1a446978f8ae.png">

**Comment by hannesdatta** [comment]
just finished and pushed to master. now can install like explained in readme.md
